---
title: "02.BetaDiversity"
author: "ifanlyn@outlook.com"
date: "2022/1/14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading packages and subroutines {.tabset}

### Packages

```{r packages, message=FALSE, warning=FALSE}
require(vegan)
require(ggplot2)
require(ochRe)
```

### FileCreate

```{r}
FileCreate <- function(DirPath = "./",Prefix = "ExampleTest", Suffix = "pdf", version = "0.0"){
  date=as.character(Sys.Date())
  DirPath = gsub("/$","",DirPath)
  Suffix = gsub('^[.]',"",Suffix)
  if(! dir.exists(DirPath)){
    dir.create(DirPath,recursive =TRUE)
  }
  if (version == "0.0") {
    version=10
    while(TRUE){
      version_=paste(unlist(strsplit(as.character(version),"")),collapse=".")
      DirPathName = paste0(DirPath,"/",date,'-',Prefix,'-v',version_,".",Suffix)
      if(! file.exists(DirPathName)){
        return(DirPathName)
        break
      }
      version = version + 1
    }
  }else{
    DirPathName = paste0(DirPath,"/",date,'-',Prefix,'-v',version,".",Suffix)
    if(! dir.exists(DirPathName)){
      return(DirPathName)
    }
    return(DirPathName)
  }
}
  
```

### ImportTable

```{r ImportTable }
ImportTable <- function(file, header = T, row.names = 1, sep = ',', check.names = FALSE, ...){
  data <- read.csv(file = file, header = header, row.names = row.names, sep = sep, check.names = check.names, ...)
  return(data)
}
```

## Import data {.tabset}

### Import metadata

```{r , message = F, warning = F}
meta_df <- ImportTable(file = '../00.RawData/metaData/2021-07-26-metaInfo-subgroup_1329-v6.0.csv')
meta_df <- meta_df[order(meta_df$Stage), ]
meta_df$Cohort <- ifelse(meta_df$Cohort == "2014_ZellerG", "2014_ZellerG", 
                        ifelse(meta_df$Cohort == "2015_FengQ", "2015_FengQ", 
                               ifelse(meta_df$Cohort == "2016_VogtmannE", "2016_VogtmannE", 
                                      ifelse(meta_df$Cohort == "2019_Thom", "2019_ThomasAM", 
                                             ifelse(meta_df$Cohort == "2019_WirbelJ", "2019_WirbelJ", 
                                                    ifelse(meta_df$Cohort == "2019_Yachida", "2019_YachidaS", 
                                                           ifelse(meta_df$Cohort == "2021_JunY_1", "2017_YuJ","2021_YuJ")))))))
# meta_df$Stage <- factor(meta_df$Stage, c("CRC", "adenoma", "CTRL"))
```

### Import otu

```{r , message = F, warning = F}
otu_df <- ImportTable('../07.FeatureSelection/02.RelMedianAbundance/2021-07-30-normalized-0.1%-RelMedianAbundance-matrix-v1.0.0.csv')
otu_df <- ImportTable('../05.Normalized/Rarefy_1329_fungi/2021-07-26-RelativeAbundance_matrix-v1.0.csv') %>% t() %>% as.data.frame()
euk_sel <- ImportTable(file = '../07.FeatureSelection/01.SSTF/2021-07-30-wilcoxon-all-v1.0.0.csv')
euk_sel <- euk_sel[order(euk_sel$adj_pvalue),]
euk_core <- euk_sel[euk_sel$adj_pvalue < 0.01, ]

core_otu <- otu_df[, rownames(euk_core)]
```

## Beta Diversity

```{r, message = F, warning = F}
otu_dist <- vegdist(core_otu, method="bray", binary=F)
otu_dist <- vegdist(otu_df, method="bray", binary=F)
otu_pcoa <- cmdscale(otu_dist, k=3, eig=T)

otu_pcoa_points <- as.data.frame(otu_pcoa$points)
sum_eig <- sum(otu_pcoa$eig)
eig_percent <- round(otu_pcoa$eig/sum_eig*100,1)
colnames(otu_pcoa_points) <- paste0("PCoA", 1:3)
otu_pcoa_result <- cbind(otu_pcoa_points, meta_df[rownames(otu_pcoa_points), ])


g <- ggplot(otu_pcoa_result, aes(x=PCoA1, y=PCoA2, color=Cohort)) +
  labs(x=paste("PCoA 1 (", eig_percent[1], "%)", sep=""),
       y=paste("PCoA 2 (", eig_percent[2], "%)", sep="")) +
  geom_point(size=2) + stat_ellipse(level=0.8) +
  theme_classic() + 
  scale_color_ochre(palette = "namatjira_qual")

g2 <- ggplot(otu_pcoa_result, aes(x=PCoA1, y=PCoA2, color=Continent)) +
  labs(x=paste("PCoA 1 (", eig_percent[1], "%)", sep=""),
       y=paste("PCoA 2 (", eig_percent[2], "%)", sep="")) +
  geom_point(size=2) + stat_ellipse(level=0.8) +
  theme_classic() +
  scale_color_ochre(palette = "lorikeet")

adon_res_cohort <- adonis(otu_dist ~ Cohort, data = otu_pcoa_result, perm = 999)
adon_res_continent <- adonis(otu_dist ~ Continent, data = otu_pcoa_result, perm = 999)
adon_res_stage <- adonis(otu_dist ~ Stage, data = otu_pcoa_result, perm = 999)
adon_res_gender <- adonis(otu_dist ~ Gender, data = otu_pcoa_result, perm = 999)
# adon_res_age <- adonis(otu_dist ~ Age, data = otu_pcoa_result[!is.na(otu_pcoa_result$Age),], perm = 999)

adon_res <- adonis2(otu_df ~ Cohort + Continent, data=otu_pcoa_result, permutations=999, by="margin")

adon_res2 <- adonis2(otu_df ~ Continent + Cohort, data=otu_pcoa_result, permutations=999, by="margin")


```







