# 2021/3/29 (Y/M/D)
# For gatric cancer


# plot compositional bar plot for phylum level bacteria
# smooth the curve
# input data generated by : GC_C_OTU_Phylum.R, GC_PCoA_6_Studies.R
# according to : GC_C_Barplot_phylum.R 






setwd("F:/GitHub/multi-CRC-fungi/00.code/changan_code/barplot_phylum")





library(dplyr)
library(gtools)  # for mixedsort()
library(reshape2)  # for melt function
library(ggplot2)
library(ggpubr)

library(RColorBrewer)
library(randomcoloR)

library(grid)




##########################--------------------------------------------------
##########################--------------------------------------------------

# input reads data for phylum level, 825 samples
Input_OTU <- read.csv("./Merged_6_Studies_OTU_level2.csv",  header = TRUE, 
                      stringsAsFactors = FALSE, check.names=FALSE)


# tranform the count data to percentage data 

Input_OTU.RA <- Input_OTU

Input_OTU.RA[, -c(1:2)] <- sweep(Input_OTU.RA[, -c(1:2)], 2, colSums(Input_OTU.RA[, -c(1:2)]),"/")*100


# 82500, sum up to 100 for each sample
sum(colSums(Input_OTU.RA[, -c(1:2)]))


order(-rowMeans(Input_OTU.RA[, -c(1:2)]))

# sort for mean relative abundance 
Input_OTU.S <- Input_OTU.RA[order(-rowMeans(Input_OTU.RA[, -c(1:2)])), ]

##########################

rowMeans(Input_OTU.S[, -c(1:2)])[1:15]

# 5 phylum with mean relative abundance > 1%
Input_OTU.S[rowMeans(Input_OTU.S[, -c(1:2)])>1, c(1,2)]


# just keep the 5 phylum

Input_OTU.S1 <- Input_OTU.S[1:5, ]

rownames(Input_OTU.S1) <- Input_OTU.S1$Phylum

P_OTU_table <- as.data.frame(t(Input_OTU.S1[, -c(1:2)]))

##########################

# input merged metadata for the 6 studies
Input_Meta <- read.csv("./GC_Metadata_Merged_6_Studies_Sort.csv", header = TRUE,
                       stringsAsFactors = FALSE, check.names=FALSE)


# TRUE
identical(rownames(P_OTU_table), Input_Meta$Sequence_ID)

P_OTU_table$Sample <- rownames(P_OTU_table)

P_OTU_table$Group <- Input_Meta$Diagnosis

table(P_OTU_table$Group)

P_OTU_table[P_OTU_table$Group == "Superficial_Gastritis", "Group"] <- "SG"

P_OTU_table[P_OTU_table$Group == "Atrophic_Gastritis", "Group"] <- "AG"

P_OTU_table[P_OTU_table$Group == "Intestinal_Metaplasia", "Group"] <- "IM"

P_OTU_table[P_OTU_table$Group == "Gastric_Cancer", "Group"] <- "GC"

P_OTU_table$Group <- factor(P_OTU_table$Group, levels = c("SG", "AG", "IM", "GC"))


###########################

barplot_data <- melt(P_OTU_table, id.vars = c("Sample","Group"), variable.name = "Phylum", value.name = "Abundance")


# test

ggplot(barplot_data, aes(x = Sample, y = Abundance, fill = Phylum))+
  geom_bar(stat = "identity", width = 1) +
  facet_grid( ~ Group, scales = "free", space = "free") + 
  theme_bw(base_size = 20)+
  theme(legend.position = "right", legend.text=element_text(size=12), legend.title=element_text(size=16),
        axis.title.x = element_blank(),strip.text = element_text(face = "bold"),
        axis.text.x = element_blank(), axis.ticks.x = element_blank(),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  ylab("Relative Abundance (%)") +
  guides(fill=guide_legend(ncol=1)) + 
  scale_fill_manual(values=get_palette("rickandmorty", 5))


##########################--------------------------------------------------

# sort by the most abundant phylum: Proteobacteria


barplot_data_N <- barplot_data

Input_OTU.S1$Phylum[1]

Phylum_top1 <- barplot_data_N[barplot_data_N$Phylum == Input_OTU.S1$Phylum[1], ]

Phylum_top1_s <- Phylum_top1[order(-Phylum_top1$Abundance), ]

Phylum_top1_order <- Phylum_top1_s$Sample


##########################

ggplot(barplot_data_N, aes(x = factor(Sample, levels = Phylum_top1_order), y = Abundance, fill = Phylum))+
  geom_bar(stat = "identity", width = 1) +
  facet_grid( ~ Group, scales = "free", space = "free") +
  theme_bw(base_size = 20)+
  theme(legend.position = "right", legend.text=element_text(size=12), legend.title=element_text(size=16),
        axis.title.x = element_blank(),strip.text = element_text(face = "bold"),
        axis.text.x = element_blank(), axis.ticks.x = element_blank(),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  ylab("Relative Abundance (%)") +
  guides(fill=guide_legend(ncol=1)) + 
  scale_fill_manual(values=get_palette("rickandmorty", 5))


##########################--------------------------------------------------
##########################--------------------------------------------------

# cluster each group

table(Input_Meta$Diagnosis)

OTU.SG <- P_OTU_table[P_OTU_table$Group == "SG",]

OTU.AG <- P_OTU_table[P_OTU_table$Group == "AG",]

OTU.IM <- P_OTU_table[P_OTU_table$Group == "IM",]

OTU.GC <- P_OTU_table[P_OTU_table$Group == "GC",]


names(OTU.SG)

# hclust method: "ward.D", "ward.D2", "single", "complete", "average","mcquitty","median","centroid"

Clust_method <- c("ward.D", "ward.D2", "single", "complete", "average","mcquitty","median","centroid")

# consider toi use "centroid"
C.M <- Clust_method[8]

Clust.SG <- hclust(dist(OTU.SG[, -c(6,7)]), method = C.M)
# plot(Clust.SG)
OTU.SG.S <- OTU.SG[Clust.SG$order, ]


Clust.AG <- hclust(dist(OTU.AG[, -c(6,7)]), method = C.M)
OTU.AG.S <- OTU.AG[Clust.AG$order, ]


Clust.IM <- hclust(dist(OTU.IM[, -c(6,7)]), method = C.M)
OTU.IM.S <- OTU.IM[Clust.IM$order, ]


Clust.GC <- hclust(dist(OTU.GC[, -c(6,7)]), method = C.M)
OTU.GC.S <- OTU.GC[Clust.GC$order, ]


P_OTU_table.C <- rbind(OTU.SG.S, OTU.AG.S, OTU.IM.S, OTU.GC.S)

barplot_data.C <- melt(P_OTU_table.C, id.vars = c("Sample","Group"), variable.name = "Phylum", value.name = "Abundance")

##########################

ggplot(barplot_data.C, aes(x = factor(Sample, levels = P_OTU_table.C$Sample), y = Abundance, fill = Phylum))+
  geom_bar(stat = "identity", width = 1) +
  facet_grid( ~ Group, scales = "free", space = "free") +
  theme_bw(base_size = 20)+
  theme(legend.position = "right", legend.text=element_text(size=12), legend.title=element_text(size=16),
        axis.title.x = element_blank(),strip.text = element_text(face = "bold"),
        axis.text.x = element_blank(), axis.ticks.x = element_blank(),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  ylab("Relative Abundance (%)") +
  guides(fill=guide_legend(ncol=1)) + 
  scale_fill_manual(values=get_palette("rickandmorty", 5)) +
  ggtitle(paste0(C.M))


##########################


P1 <- ggplot(barplot_data.C, aes(x = factor(Sample, levels = P_OTU_table.C$Sample), y = Abundance, fill = Phylum))+
  geom_bar(stat = "identity", width = 1) +
  facet_grid( ~ Group, scales = "free", space = "free") +
  theme_bw(base_size = 10)+
  theme(legend.position = "right", legend.text=element_text(size=6), legend.title=element_text(size=8),
        axis.title.x = element_blank(),strip.text = element_text(face = "bold"),
        axis.text.x = element_blank(), axis.ticks.x = element_blank(),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.spacing.x = unit(0, "lines"))+
  ylab("Relative Abundance (%)") +
  guides(fill=guide_legend(ncol=1)) + 
  scale_fill_manual(values=get_palette("rickandmorty", 5)) 
  

G1 <- ggplot_gtable(ggplot_build(P1))

G1$layout

stripr <- which(grepl('strip-t', G1$layout$name))

fills <- c("cyan","forestgreen","orange","red")

k <- 1

for (i in stripr) {
  j <- which(grepl('rect', G1$grobs[[i]]$grobs[[1]]$childrenOrder))
  G1$grobs[[i]]$grobs[[1]]$children[[j]]$gp$fill <- fills[k]
  k <- k+1
}

grid.newpage()
grid.draw(G1)

ggsave("./GC_C_Barplot_Phylum_Clust.pdf", G1, width = 200, height = 50, units = "mm")


##########################--------------------------------------------------
##########################--------------------------------------------------

# smooth the curve
# according to : http://r-statistics.co/Loess-Regression-With-R.html

dim(OTU.SG.S)
OTU.SG.S_pred <- OTU.SG.S

for (line in rev(1:5)) {
  x <- 1:dim(OTU.SG.S)[1]
  y = unlist(OTU.SG.S_pred[, line], use.names = F)
  
  lo <- loess(y~x, span=0.25)
  pred_y = predict(lo)
  pred_y[pred_y < 0] <- 0
  OTU.SG.S_pred[,line] <- pred_y
}



OTU.AG.S_pred <- OTU.AG.S

for (line in rev(1:5)) {
  x <- 1:dim(OTU.AG.S)[1]
  y = unlist(OTU.AG.S_pred[, line], use.names = F)
  
  lo <- loess(y~x, span=0.25)
  pred_y = predict(lo)
  pred_y[pred_y < 0] <- 0
  OTU.AG.S_pred[,line] <- pred_y
}



OTU.IM.S_pred <- OTU.IM.S

for (line in rev(1:5)) {
  x <- 1:dim(OTU.IM.S)[1]
  y = unlist(OTU.IM.S_pred[, line], use.names = F)
  
  lo <- loess(y~x, span=0.25)
  pred_y = predict(lo)
  pred_y[pred_y < 0] <- 0
  OTU.IM.S_pred[,line] <- pred_y
}


OTU.GC.S_pred <- OTU.GC.S

for (line in rev(1:5)) {
  x <- 1:dim(OTU.GC.S)[1]
  y = unlist(OTU.GC.S_pred[, line], use.names = F)
  
  lo <- loess(y~x, span=0.25)
  pred_y = predict(lo)
  pred_y[pred_y < 0] <- 0
  OTU.GC.S_pred[,line] <- pred_y
}


P_OTU_table.S <- rbind(OTU.SG.S_pred, OTU.AG.S_pred, OTU.IM.S_pred, OTU.GC.S_pred)

# 28
sum(rowSums(P_OTU_table.S[, c(1:5)])>100)

P_OTU_table.S1 <- P_OTU_table.S

P_OTU_table.S1[rowSums(P_OTU_table.S1[, c(1:5)])>100, 1] <- 100 - rowSums(P_OTU_table.S1[rowSums(P_OTU_table.S1[, c(1:5)])>100, c(2:5)])

# 0
sum(rowSums(P_OTU_table.S1[, c(1:5)])>100)


barplot_data.S <- melt(P_OTU_table.S1, id.vars = c("Sample","Group"), variable.name = "Phylum", value.name = "Abundance")

##########################

ggplot(barplot_data.S, aes(x = factor(Sample, levels = P_OTU_table.S$Sample), y = Abundance, fill = Phylum))+
  geom_bar(stat = "identity", width = 1) +
  facet_grid( ~ Group, scales = "free", space = "free") +
  theme_bw(base_size = 20)+
  theme(legend.position = "right", legend.text=element_text(size=12), legend.title=element_text(size=16),
        axis.title.x = element_blank(),strip.text = element_text(face = "bold"),
        axis.text.x = element_blank(), axis.ticks.x = element_blank(),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  ylab("Relative Abundance (%)") +
  guides(fill=guide_legend(ncol=1)) + 
  scale_fill_manual(values=get_palette("rickandmorty", 5)) 
  


##########################

P2 <- ggplot(barplot_data.S, aes(x = factor(Sample, levels = P_OTU_table.S$Sample), y = Abundance, fill = Phylum))+
  geom_bar(stat = "identity", width = 1) +
  facet_grid( ~ Group, scales = "free", space = "free") +
  theme_bw(base_size = 10)+
  theme(legend.position = "right", legend.text=element_text(size=6), legend.title=element_text(size=8),
        axis.title.x = element_blank(),strip.text = element_text(face = "bold"),
        axis.text.x = element_blank(), axis.ticks.x = element_blank(),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.spacing.x = unit(0, "lines"))+
  ylab("Relative Abundance (%)") +
  guides(fill=guide_legend(ncol=1)) + 
  scale_fill_manual(values=get_palette("rickandmorty", 5)) +
  scale_y_continuous(limits = c(0, 100))



G2 <- ggplot_gtable(ggplot_build(P2))

G2$layout

stripr <- which(grepl('strip-t', G2$layout$name))

fills <- c("cyan","forestgreen","orange","red")

k <- 1

for (i in stripr) {
  j <- which(grepl('rect', G2$grobs[[i]]$grobs[[1]]$childrenOrder))
  G2$grobs[[i]]$grobs[[1]]$children[[j]]$gp$fill <- fills[k]
  k <- k+1
}

grid.newpage()
grid.draw(G2)

ggsave("./GC_C_Barplot_Phylum_Clust_Smooth.pdf", G2, width = 200, height = 50, units = "mm")


##########################

P3 <- ggplot(barplot_data.S, aes(x = factor(Sample, levels = P_OTU_table.S$Sample), y = Abundance, fill = Phylum))+
  geom_bar(stat = "identity", width = 1) +
  facet_grid( ~ Group, scales = "free", space = "free") +
  theme_bw(base_size = 10)+
  theme(legend.position = "right", legend.text=element_text(size=8), legend.title=element_text(size=8),
        axis.title.x = element_blank(),strip.text = element_text(face = "bold"),
        axis.text.x = element_blank(), axis.ticks.x = element_blank(),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.spacing.x = unit(0, "lines"))+
  ylab("Relative Abundance (%)") +
  guides(fill=guide_legend(ncol=1)) + 
  scale_fill_manual(values=get_palette("rickandmorty", 5)) +
  scale_y_continuous(limits = c(0, 100))



G3 <- ggplot_gtable(ggplot_build(P3))

G3$layout

stripr <- which(grepl('strip-t', G3$layout$name))

fills <- c("cyan3","forestgreen","orange","red")

k <- 1

for (i in stripr) {
  j <- which(grepl('rect', G3$grobs[[i]]$grobs[[1]]$childrenOrder))
  G3$grobs[[i]]$grobs[[1]]$children[[j]]$gp$fill <- fills[k]
  k <- k+1
}

grid.newpage()
grid.draw(G3)

ggsave("./GC_C_Barplot_Phylum_Clust_Smooth_N.pdf", G3, width = 200, height = 50, units = "mm")
